### ISSUE TITLE
 online notebook problem with hitran db

### ISSUE THREAD

**Issue by arunavabasu-03** [radis/radis#491] opened 2022-07-01 14:34 UTC
### 🐛 Describe the bug

hey team , when I am running radis in the local system it runs fine with every database but when I try to run it on **any online notebook (deepnote , Google collab )** then for **database= "hitran"** it gives errors[buffer error] and other database like geisa it runs fine.
<p align="center">
<img width="45%" alt="Screenshot 2022-07-01 at 7 44 54 PM" src="https://user-images.githubusercontent.com/73842340/176913724-ea028246-f31f-4523-b1fc-87b3770d95da.png"> 
<img width="45%" alt="Screenshot 2022-07-01 at 7 48 44 PM" src="https://user-images.githubusercontent.com/73842340/176913757-50a47810-91fb-4430-88d3-ae5252d7c909.png">
 </p>

### 🎲 Radis version

0.13.0

### 💻 Operating system

MacOS

**Comment by arunavabasu-03** [comment] 2022-07-01 16:24
<img width="753" alt="Screenshot 2022-07-01 at 9 53 53 PM" src="https://user-images.githubusercontent.com/73842340/176933494-2d2cabb7-26e7-4c8c-a933-4c7716f4faee.png">

**Comment by arunavabasu-03** [comment] 2022-07-01 16:26
####  👉 Logs :
```
HAPI version: 1.2.2.0
To get the most up-to-date version please check http://hitran.org/hapi
ATTENTION: Python versions of partition sums from TIPS-2021 are now available in HAPI code

           MIT license: Copyright 2021 HITRAN team, see more at http://hitran.org. 

           If you use HAPI in your research or software development,
           please cite it using the following reference:
           R.V. Kochanov, I.E. Gordon, L.S. Rothman, P. Wcislo, C. Hill, J.S. Wilzewski,
           HITRAN Application Programming Interface (HAPI): A comprehensive approach
           to working with spectroscopic data, J. Quant. Spectrosc. Radiat. Transfer 177, 15-30 (2016)
           DOI: 10.1016/j.jqsrt.2016.03.005

           ATTENTION: This is the core version of the HITRAN Application Programming Interface.
                      For more efficient implementation of the absorption coefficient routine, 
                      as well as for new profiles, parameters and other functional,
                      please consider using HAPI2 extension library.
                      HAPI2 package is available at http://github.com/hitranonline/hapi2

Using /root/.radisdb/hitran/downloads__can_be_deleted/CO


Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_1
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_1.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_1.data
Header written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_1.header
END DOWNLOAD
                     Lines parsed: 1344
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_2
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_2.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_2.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_2.data
Header written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_2.header
END DOWNLOAD
                     Lines parsed: 1042
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_3
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_3.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_3.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_3.data
Header written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_3.header
END DOWNLOAD
                     Lines parsed: 920
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_4
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_4.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_4.data
Header written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_4.header
END DOWNLOAD
                     Lines parsed: 800
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_5
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_5.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_5.data
Header written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_5.header
END DOWNLOAD
                     Lines parsed: 674
PROCESSED

Data is fetched from http://hitran.org

BEGIN DOWNLOAD: CO_6
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_6.data
  65536 bytes written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_6.data
Header written to /root/.radisdb/hitran/downloads__can_be_deleted/CO/CO_6.header
END DOWNLOAD
                     Lines parsed: 601
PROCESSED
BufferError: cannot close exported pointers exist
```

**Comment by erwanp** [comment] 2022-07-01 16:42
Thank you. And what is the Numpy version ? Could be related to https://github.com/radis/radis/pull/490  if numpy>1.22.3

**Comment by arunavabasu-03** [comment] 2022-07-01 17:16
<img width="781" alt="Screenshot 2022-07-01 at 10 45 56 PM" src="https://user-images.githubusercontent.com/73842340/176940684-0fd681f6-75b4-45d2-944f-3f9fe505fcfd.png">

**Comment by arunavabasu-03** [comment] 2022-07-01 17:19
> Could be related to #490 if numpy>1.22.3

not sure @erwanp

**Comment by erwanp** [comment] 2022-07-01 18:24
Can you retry with numpy<1.22.3?

**Comment by arunavabasu-03** [comment] 2022-07-01 19:08
@erwanp working fine in numpy<1.22.3 !

<img width="718" alt="Screenshot 2022-07-02 at 12 37 37 AM" src="https://user-images.githubusercontent.com/73842340/176955675-2c365b5e-9aac-43b8-9791-9f56668d815f.png">

**Comment by erwanp** [comment] 2022-07-02 10:35
Can you update the dependencies to make sure we have numpy<1.22.3 in your install too?

**Comment by arunavabasu-03** [comment] 2022-07-02 12:06
you taking about to update this [link](https://github.com/radis/radis/blob/b853a26b34a0b9b53670062a2214da4d134ec391/setup.py#L256)

**Comment by erwanp** [comment] 2022-07-02 13:58
If it's already there, how come your test install used a newer version of numpy?

**Comment by arunavabasu-03** [comment] 2022-07-03 15:03
no idea @erwanp

**Comment by erwanp** [comment] 2022-07-03 18:05
Please try to find out ? If you can't reproduce it, you can safely close the issue !

**Comment by arunavabasu-03** [comment] 2022-07-03 18:37
ok, @erwanp, I try to find it out but for now, I close the issue 😀 .

**Closed** 2022-07-03 18:38 UTC
Labels: bug, help wanted, db:hitran, databases
