### ISSUE TITLE
Bug Report: GPU emulation tries to import cython

### ISSUE THREAD

**Issue by minouHub** [radis/radis#583] opened 2023-07-25 14:27 UTC
### 🐛 Describe the bug

This code tries to import cython, although it was not installed on my computer.
```python
from radis import SpectrumFactory
 
sf = SpectrumFactory(
   2150,
   2450, # cm-1
   molecule="CO2",
   isotope="1,2,3",
   wstep=0.002,
)
 
sf.fetch_databank("hitemp")
 
s = sf.eq_spectrum_gpu(
   Tgas=1100.0, # K
   pressure=1, # bar
   mole_fraction=0.8,
   path_length=0.2, # cm
   emulate=True, # if True, runs CPU code on GPU. Set to False or remove to run on the GPU
)
print(s)
 
s.apply_slit(0.5) # cm-1
s.plot("radiance", show=True)
```
Output:
```python
Traceback (most recent call last):

  File C:\Anaconda\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\nicolas minesi\desktop\nextcloud\2-radis_paper_figures\comparison_spectra.py:58
    s = sf.eq_spectrum_gpu(

  File c:\users\nicolas minesi\python\radis\lbl\factory.py:1150 in eq_spectrum_gpu
    gpu_init(

  File c:\users\nicolas minesi\python\radis\lbl\gpu.py:469 in gpu_init
    from radis_cython_extensions import set_init_params  # isort:skip

ModuleNotFoundError: No module named 'radis_cython_extensions'
```

### 🎲 Radis version

0.14-g0b87b6f9

### 💻 Operating system

Windows

**Comment by erwanp** [comment] 2023-07-25 22:45
could try a fix similar to this: https://github.com/radis/radis/blob/0b87b6f9e0541fce9f6c9e8b7be30ffefbdd3c30/radis/lbl/gpu.py#L143

**Comment by dcmvdbekerom** [comment] 2023-07-26 06:28
@minouHub you are running in emulate mode without having compiles the code. Changing the keyword to emulate=True will fix the issue.

This is technically not a bug, because the idea of the emulate mode is that it runs the same GPU c++ code (i.e. GPU.cpp), except on the CPU. Falling back to python is not a good option here imho.

 A better warning would be good though.

Also, we could consider packing a portable c++ compiler with radis. It's surprising to me cython doesn't come with a compiler itself. The advantage of this is that everyone gets the speedups associated with compiled code (like the new add_at)

**Comment by minouHub** [comment] 2023-07-26 06:52
with `emulate=False`:

```python
Traceback (most recent call last):

  File C:\Anaconda\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\nicolas minesi\desktop\nextcloud\2-radis_paper_figures\untitled2.py:20
    s = sf.eq_spectrum_gpu(

  File c:\users\nicolas minesi\python\radis\lbl\factory.py:1150 in eq_spectrum_gpu
    gpu_init(

  File c:\users\nicolas minesi\python\radis\lbl\gpu.py:449 in gpu_init
    from cupy import RawModule, array, complex64, float32, zeros

ModuleNotFoundError: No module named 'cupy'
```

Sorry, I'm approaching this problem with a simple user approach: "does it work?" "yes/no". I agree that a more developed warning would help: `XXX is missing. You might have forgotten to do XXX. Run this command 'XXX' and try again.`

**Comment by dcmvdbekerom** [comment] 2023-07-26 07:55
> I'm approaching this problem with a simple user approach

Like you should!

The problem now is you don't have cupy installed.
https://docs.cupy.dev/en/stable/install.html

Note that you need to install Nvidia CUDA before installing cupy.
https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html

I suppose in the future we could look into packing prebuilt kernels to not have to install the entire CUDA sdk but that will take some work

**Comment by dcmvdbekerom** [comment] 2023-07-26 08:04
>I suppose in the future we could look into packing prebuilt kernels to not have to install the entire CUDA sdk but that will take some work

Following up on this, @minouHub if you *don't* install any of that we could keep your system as a testbed to check if the prebuilt kernels work.

I could look into this some time next week, if that's not too late it's worth investigating

**Comment by minouHub** [comment] 2023-07-26 10:41
Alright, I volunteer to *not* install CUDA and cupy until you propose a warning/error message to guide a new user. I'll follow the instruction and see if it works (I have a nvidia card btw)

**Comment by dcmvdbekerom** [comment] 2023-08-01 11:06
Since this is not technically a bug, I'll close this one and continue discussion here https://github.com/radis/radis/issues/596

**Closed by dcmvdbekerom** 2023-08-01 11:06 UTC
Labels: bug
