### ISSUE TITLE
Error, NaN generated for spectra around 2000nm

### ISSUE THREAD

**Issue by CorentinGrimaldi** [radis/radis#47] opened 2019-09-06 07:57 UTC
This really simple code causes a crash :
```
from radis import calc_spectrum
s = calc_spectrum(wavelength_min=1800,
                   wavelength_max=2200,
                   Tgas=6000,
                   Trot=6000,
                   Tvib=6000.01,
                   pressure=1,
                   molecule='CO2',
                   isotope='1',
                   path_length=1,
                   mole_fraction=400e-6,
                   )
```
A NaN is generated when fetching Evib & Erot :
```
Fetching Evib & Erot.
Traceback (most recent call last):

  File "<ipython-input-1-65ff9c77bd85>", line 11, in <module>
    mole_fraction=400e-6,

  File "/home/corentin/Documents/radis/radis/lbl/calc.py", line 370, in calc_spectrum
    name=name)

  File "/home/corentin/Documents/radis/radis/lbl/factory.py", line 866, in non_eq_spectrum
    self._check_noneq_parameters(vib_distribution, singleTvibmode)

  File "/home/corentin/Documents/radis/radis/lbl/base.py", line 1389, in _check_noneq_parameters
    self._calc_noneq_parameters(calc_Evib_harmonic_anharmonic=calc_Evib_harmonic_anharmonic)

  File "/home/corentin/Documents/radis/radis/lbl/base.py", line 1438, in _calc_noneq_parameters
    self._add_EvibErot(df, calc_Evib_harmonic_anharmonic=calc_Evib_harmonic_anharmonic)

  File "/home/corentin/Documents/radis/radis/lbl/base.py", line 346, in _add_EvibErot
    return self._add_Evib123Erot_RADIS_cls5(df)

  File "/home/corentin/Documents/radis/radis/lbl/base.py", line 1138, in _add_Evib123Erot_RADIS_cls5
    assert np.isnan(df.Evib1l).sum() == 0

AssertionError
```
The error is perhaps with the HITRAN database...

**Comment by erwanp** [comment] 2019-09-06 09:13
Hello @CorentinGrimaldi , thanks for reporting!

The error is raised because the vibrational energy of a specific level couldnt be determined. 
After thorough investigation, the level appears in this line of the HITRAN database:
```
21 5029.149081 3.847e-28 1.838e-04.06830.084 1805.25230.76-.005913       2 2 2 12       1 0 2 02
```
where the lower level is 10'2'0. This level does not exist (v2 = 0, l2 = 2) in either the HITRAN or usual spectrosopic notation. Two conclusions here:

- there seems to be a (typo?) error in the HITRAN database for this line. 
- the RADIS error is not explicit and should be more documented. 

Actions:
- [ ] Contact the HITRAN team 
- [ ] improve RADIS to crash with a more explicit message.

**Comment by erwanp** [comment] 2019-09-10 06:42
The HITRAN team confirmed that the correct labelling should be 
```
21 5029.149081 3.847E-28 1.838e-04.06830.084 1805.25230.76-.005913       2 2 2 12       1 0 0 02
```
This will be fixed in the next version.

**Closed** 2019-11-04 14:07 UTC
Labels: bug, db:hitran
