### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by erwanp** [radis/radis#46] opened 2019-09-05 19:32 UTC
Drop-in GPU alternatives for most CPU-intensive tasks:

- [ ] when using DLM, replace `numpy.add.at` with [cupyx.scatter_add](https://docs-cupy.chainer.org/en/stable/reference/generated/cupyx.scatter_add.html) 

An alternative is to use `numba` which also has GPU support:

- [ ] for Voigt calculations: http://numba.pydata.org/numba-doc/latest/cuda/index.html

---

Edit : 

### Being worked on in #117 

_Dedicated Slack channel : https://radis-radiation.slack.com/archives/C018X7XGMBP_

**Comment by dcmvdbekerom** [comment] 2019-09-05 20:58
Sounds promising! Any idea how much it would be sped up?

**Comment by erwanp** [comment] 2019-09-06 14:14
[This study](https://blog.dask.org/2019/06/27/single-gpu-cupy-benchmarks) shows speedups of x5 for FFT, x8 for sum, and x150 for elementwise operations for arrays of ~8 MB. That's about 1M lines. The large performance improvements are only obtained for much larger arrays, but we probably won't ever use that. 
Also, I'm concerned about transfer loss to the GPU: we'll only see after a first implementation if we actually speed up the thing

**Comment by dcmvdbekerom** [comment] 2019-09-06 14:42
Not too bad! 
> we'll only see after a first implementation
Yep you're right!

By the way, there's this note on the [scatter_add](https://docs-cupy.chainer.org/en/stable/reference/generated/cupyx.scatter_add.html) function:

> It only supports types that are supported by CUDA’s atomicAdd when an integer array is included in slices. The supported types are numpy.float32, numpy.int32, numpy.uint32, numpy.uint64 and numpy.ulonglong.

I think the standard representation for floating point numbers is double64 in python/numpy, which seems to be incompatible with scatter_add. Then again, sacrificing that resolution may not be noticeable in the grand scheme of things.

**Comment by dcmvdbekerom** [comment] 2020-02-22 01:40
For GPU support, there are two options:

1. Calculate the spectral data (intensity, position, and G+L widths) for every line by CPU, and do everything else with the GPU. The advantage of this is that the particulars of the spectral model can all be done in Python (on the CPU), which maximizes flexibility. The problem is that for large line lists, transferring this spectral data from RAM to the GPU becomes a bottleneck, limiting the optimization that is possible by using the GPU.

2. Transfer the entire database to the GPU and calculate the spectral data on the GPU, in addition to the summations and linehapes etc. Transferring the entire database may take a while initially (i.e. ~a dozen seconds), but after that spectra can be calculated extremely fast. This is ideal if you need a lot of different spectra using the same database, like when fitting profiles or calculating line-of-sight spectra. The disadvantage is that almost all code for generating the spectrum will be ran on the GPU, so is generally less flexible.

Another point to consider is that as far as I can tell, CuPy does not support so called "constant memory" on the GPU, which should be used for distributing certain variables (e.g. pressure, temperature) along all the threads. This means that to maximize GPU performance the code would have to be in CUDA C rather than CuPy, which again means less flexibility.

**Comment by erwanp** [comment] 2020-04-18 14:36
(this will be worked on in a [Google Summer of Code 2020](https://openastronomy.org/gsoc/gsoc2020/#/projects?project=radis_atmosphere_calculation_interface) project)

**Closed** 2020-08-31 14:46 UTC
Labels: performance
