### ISSUE TITLE
Automatize CO2 / H2O download for HITEMP 

### ISSUE THREAD

**Issue by erwanp** [radis/radis#210] opened 2021-03-05 15:41 UTC
### 🎯 Describe what you'd like

Automatic download of HITEMP was introduced in #203 . 
It works for N2O, NO, CO, CH4, NO2, OH (single-file .bz2 ) but not H2O and CO2 (multi-file zips)

### 💡 Possible implementations

Improve the [fetch_hitemp](https://github.com/radis/radis/blob/develop/radis/io/hitemp.py#L82) function to :  
- work with multiple files (quite easy)
- work with *zip files (the current implementation with `numpy.DataSource` does not handle zip files, a parallel implementation or a subclass should be written)

--- 

Good First issue, no requirement in spectroscopy, but requires some Python proficiency !

**Comment by dcmvdbekerom** [comment] 2021-03-05 16:15
This script I wrote for downloading CDSD4000 might be useful:

```
import urllib.request
import re
import sys
from zipfile import ZipFile
import os
from io import BytesIO

# Spectral range to download:
lower_bound = 1750
upper_bound = 2400

# Set the URL you want to webscrape from
url = 'ftp://ftp.iao.ru/pub/CDSD-4000/'
output = './par/'

if not os.path.exists(output):
    os.mkdir(output)

# Connect to the URL
print('Fetching filelist...')
response = urllib.request.urlopen(url)

# Make list of all the files available for download on the FTP server:
fnames = re.findall('\S+.zip',response.read().decode())
for fname in fnames:

    #Check if the current file is within our spectral range of interest:
    low,high = map(float,re.findall('\d+',fname))
    if high > lower_bound and low < upper_bound:

        #Test if it doesn't exist already:
        if not os.path.exists(output+fname[:-4]):

            #Start downloading!
            print('Downloading '+fname[:-4]+'...',end='')
            fzip = BytesIO(urllib.request.urlopen(url+fname).read())
            ZipFile(fzip).extractall(output)
            print(' Done!'),
        else:
            print(fname[:-4]+' already exists, skipping!')
print('Done!')
```

It keeps the file in memory (so not on disk) until it is unzipped

**Comment by erwanp** [comment] 2021-03-06 17:59
Nice, thank you for sharing this!

**Comment by angad11121** [comment] 2021-03-23 16:51
I'd like to help with this.

**Comment by erwanp** [comment] 2021-03-24 21:48
Exactly, but they should be unzipped. 

Currently [fetch_hitemp uses numpy.DataSource](https://github.com/radis/radis/blob/develop/radis/io/hitemp.py#L270), which does not handle .zip files. 

Maybe the most elegant way would be to subclass DataSource to also handle zip files ?

**Comment by angad11121** [comment] 2021-03-26 10:52
I checked the documentation of [DataSource](https://github.com/numpy/numpy/blob/cb557b79fa0ce467c881830f8e8e042c484ccfaa/numpy/lib/_datasource.py) in NumPy. Turns out that DataSource class just acts as an interface class and has a dependency on the _FileOpeners class which is not provided as a module by NumPy. Is it fine to just have a local copy of _datasource.py edited to our needs in this repo?


</br> </br>

P.S. NumPy actually is working on .zip support 😂
![image](https://user-images.githubusercontent.com/50276105/112621119-6439c400-8e4f-11eb-877b-e33e7f3ff2c7.png)

**Comment by erwanp** [comment] 2021-03-26 13:42
Rather than copying the whole _datasource.py,  you could subclass numpy DataSource, and add your own opener.  

Something like : 
```python
class DataSourceRadis(numpy.DataSource)

def __init__(*args, **kwargs):
    super(DataSourceRadis, self).__init__(*args, **kwargs)
    self._file_openers[".zip"] = #your function 

``` 

It it works well, you can then push and contribute to Numpy directly ! (they wrote "Todo" but I don't think it's actively being worked on?)

**Comment by erwanp** [comment] 2021-03-28 09:51
@angad11121 I'm assigning you on this temporarily, so that people now someone is already having a look at it !

**Comment by angad11121** [comment] 2021-04-22 18:25
Yup, working on it. Was busy a few days back but free now. Will update with progress soon!

**Comment by erwanp** [comment] 2021-04-22 19:44
Nice,  good luck! Please let me know if I can be of any help

**Comment by minouHub** [comment] 2021-05-25 00:17
@dcmvdbekerom, is your code in RADIS or is it personal?

**Comment by dcmvdbekerom** [comment] 2021-05-25 04:29
The code I posted above was a personal code, I believe @angad11121 is implementing this or something similar in RADIS.

**Comment by erwanp** [comment] 2021-05-26 19:03
Angad quite busy at the moment, the Issue is now up to be taken again !

**Comment by dcmvdbekerom** [comment] 2021-06-01 05:58
### 🐛 Describe the bug

I started working on automatic fetching of HITEMP databases for CO2 and H2O.
I run into an error that for certain database files, RADIS is unable to parse the file and throws an error.

### 🖥 Steps To Reproduce
I used the following branch to download the multiple files: https://github.com/dcmvdbekerom/radis/tree/auto-fetch-hitemp
And the code below to fetch the database:
```
from radis import SpectrumFactory

sf = SpectrumFactory(1900, 2300, # cm-1
                  molecule='CO2',
                  isotope='1,2,3',
                  wstep=0.002,
                  )

sf.fetch_databank('hitemp',
                  )

s = sf.eq_spectrum(Tgas=1200, #K 
                       pressure=0.2, #bar 
                       mole_fraction=0.1,
                       path_length= 2.0, #cm
                       )
s.plot('abscoeff')

```

Once the downloader reaches the file `02_01000-01500_HITEMP2010.zip`, it throws the following error:
```
(114s)  30.1%   Parsed 3,374,322 / 11,193,608 lines. Wavenumber range 1000.00-1249.41 cm-1 is complete.Traceback (most recent call last):
  File "C:\Users\dcmvd\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\pytables.py", line 3990, in _get_blocks_and_items
    b, b_items = by_items.pop(items)
KeyError: ('A', 'El', 'Pshft', 'Tdpair', 'airbrd', 'gp', 'gpp', 'int', 'l2u', 'ru', 'selbrd', 'v1u', 'v2u', 'v3u')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_spectrum_factory.py", line 11, in <module>
    sf.fetch_databank('hitemp',
  File "c:\users\dcmvd\documents\github\radis\radis\lbl\loader.py", line 975, in fetch_databank
    return_local_path=True,
  File "c:\users\dcmvd\documents\github\radis\radis\io\hitemp.py", line 373, in fetch_hitemp
    )
  File "C:\Users\dcmvd\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\pytables.py", line 1106, in put
    dropna=dropna,
  File "C:\Users\dcmvd\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\pytables.py", line 1755, in _write_to_group
    track_times=track_times,
  File "C:\Users\dcmvd\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\pytables.py", line 4224, in write
    data_columns=data_columns,
  File "C:\Users\dcmvd\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\pytables.py", line 3852, in _create_axes
    block_obj, table_exists, new_non_index_axes, self.values_axes, data_columns
  File "C:\Users\dcmvd\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\io\pytables.py", line 3998, in _get_blocks_and_items
    ) from err
ValueError: cannot match existing table structure for [A,El,Pshft,Tdpair,airbrd,gp,gpp,int,l2u,ru,selbrd,v1u,v2u,v3u] on appending data
```

### 🎯 Expected behavior
The first 4 files are unzipped and parsed without problems, which makes me think it's a problem with the formatting of the data in the HITEMP database. 

Could this be related to https://github.com/radis/radis/issues/111?

**Comment by erwanp** [comment] 2021-06-01 07:08
Note that "v1u, v2u, v3u" have been prperly parsed according to the error message, but "v1l,v2l,v3l" are missing . Can you load the already downloaded database files and print the columns ? (by %debug in interactive mode for instance). I'd like to know if something may happened in the parsing of the first 4 files that prevented to create the columns for local quantum numbers ",v1u,v2u,v3u". We'd still see the "locu", "locl" names.

You may want to create a new issue from your message ("..." options on GitHub let you "Reference in new issue")

**Comment by dcmvdbekerom** [comment] 2021-06-04 06:21
Found it! It was indeed related to https://github.com/radis/radis/issues/111, but surprisingly also to https://github.com/radis/radis/issues/118... Will write a full summary tomorrow.

**Comment by minouHub** [comment] 2021-08-20 05:16
Hello, 
I thought this feature was merged but I cannot fetch HITEMP automatically. 

radis-0.9.29 e1c57e4a

```python
from radis import calc_spectrum
s = calc_spectrum(wavenum_min=2380, 
                  wavenum_max=2385,     
                  molecule='CO2',
                  isotope='1,2,3',
                  pressure=1.01325,   # bar
                  Tgas=700,           # K
                  mole_fraction=0.1,
                  path_length=1,      # cm
                  databank='hitemp',  # or use 'hitemp'
                  wstep=0.001,
                  )
Traceback (most recent call last):

  File "e:\python\radis\radis\io\dbmanager.py", line 91, in get_filenames
    assert "download_url" in entries

AssertionError


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-12-f49bd82ce853>", line 2, in <module>
    s = calc_spectrum(wavenum_min=2380,

  File "e:\python\radis\radis\lbl\calc.py", line 435, in calc_spectrum
    _calc_spectrum(

  File "e:\python\radis\radis\lbl\calc.py", line 627, in _calc_spectrum
    sf.fetch_databank(**conditions)

  File "e:\python\radis\radis\lbl\loader.py", line 1017, in fetch_databank
    df, local_path = fetch_hitemp(

  File "e:\python\radis\radis\io\hitemp.py", line 488, in fetch_hitemp
    local_files, urlnames = ldb.get_filenames()

  File "e:\python\radis\radis\io\dbmanager.py", line 97, in get_filenames
    raise DeprecatedFileWarning(

DeprecatedFileWarning: Database file {0} not valid anymore
```

**Comment by erwanp** [comment] 2021-08-20 10:24
Looks like it's working but it's a different error. The error message itself is missing a ".format()" so hard to tell what happened !

**Comment by minouHub** [comment] 2021-08-22 20:03
Very sorry about this. The problem was that I named a personal database "HITEMP-CO2" in radis.json.

**Closed by minouHub** 2021-08-22 20:03 UTC
Labels: enhancement, good first issue, db:hitemp, databases
